### PR TITLE
Don't block the UI thread during bootstrap

### LINKED ISSUE #103: Intra can become non-responsive if the default server isn't reachable
Observed behavior:
If the default server isn't reachable during the initial setup flow, the OS can interpret intra as non-responsive.  Users also can't cancel the connection and are not offered another choice.

Expected behavior:
1. Remain responsive, and allow users to cancel a connection and change the desired server.
2. Time-out more quickly with a detailed notification to suggest changing the server.

### PR DESCRIPTION
**Pull request by bemasc**
Fixes #103

### CODE REVIEW

File: Android/app/src/main/java/app/intra/DnsVpnService.java [hunk 1]
```diff
@@ -53,13 +53,35 @@
   private static final String LOG_TAG = "DnsVpnService";
   private static final int SERVICE_ID = 1; // Only has to be unique within this app.
   private static final String CHANNEL_ID = "vpn";
+  private static final String NO_PENDING_CONNECTION = "This value is not a possible URL.";
```
Comment (alalamav) [inline Android/app/src/main/java/app/intra/DnsVpnService.java]: nit: maybe use a more standard sentinel value like `""` or `null`?

File: Android/app/src/main/java/app/intra/DnsVpnService.java [hunk 2]
```diff
@@ -53,13 +53,35 @@
...
 
+  // The network manager is populated in onStartCommand.  Its main function is to enable delayed
```
Comment (alalamav) [inline Android/app/src/main/java/app/intra/DnsVpnService.java]: nice commenting ;)

File: Android/app/src/main/java/app/intra/DnsVpnService.java (hunk 1 above)
Comment (bemasc) [reply Android/app/src/main/java/app/intra/DnsVpnService.java]: Unfortunately that doesn't work here because `null` and `""` are both treated as meaning "default server".
